stages:
    - test

flatpak:master:
    image: registry.gitlab.com/alatiera/gnome-nightly-oci/gnome-master:latest
    stage: test
    script:
    - flatpak-builder --force-clean --repo=repo app build-aux/flatpak/org.gnome.Builder.json
    - flatpak build-bundle repo builder-dev.flatpak org.gnome.Builder
    artifacts:
        paths:
          - builder-dev.flatpak
        expire_in: 2 days

    cache:
        # JOB_NAME - Each job will have it's own cache
        # COMMIT_REF_SLUG = Lowercase name of the branch
        # ^ Keep diffrerent caches for each branch
        key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
        paths:
          - .flatpak-builder/cache/